language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - PACKAGES="Django>=1.7,<1.8 django-contrib-comments<1.8"
  - PACKAGES="Django>=1.8,<1.9"
  - PACKAGES="Django>=1.9,<1.10"
  - PACKAGES="Django>=1.10,<1.11"
matrix:
  exclude:
  - python: '3.5'
    env: PACKAGES="Django>=1.7,<1.8 django-contrib-comments<1.8"

install:
  - travis_retry pip install coveralls $PACKAGES -e .

script:
  - coverage run --source=threadedcomments runtests.py

after_success:
  - coveralls --verbose

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#django-fluent"
    template:
      - "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
    skip_join: true
  email:
    recipients:
      - travis@edoburu.nl
    on_success: never
    on_failure: always
